CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -O2 \
  -I"C:/Users/Kevin Erazo/OneDrive - yachaytech.edu.c /Yachay Tech/5) Quinto Semestre/Programacion Avanzada/Universidad/Assignments/Code Challenge - L16"

all: main

main: main.cpp
	$(CXX) $(CXXFLAGS) main.cpp -o main

clean:
	rm -f main
